version: '3.7'

services:
  nest:
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - nest-network
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USERNAMEDB=${USERNAMEDB}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - PASSWORDEMAIL= ${PASSWORDEMAIL}
      - USERTRANSPORT= ${USERTRANSPORT}
      - FROMTRANSPORT= ${FROMTRANSPORT}
      - PORTTRANSPORT= ${PORTTRANSPORT}
    deploy:
      resources:
        limits:
          # mega
          memory: 512M
networks:
  nest-network:
    driver: bridge
