version: '3.7'

services:
  nest:
    build: ./ruta-de-tu-servicio-nest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USERNAMEDB=${USERNAMEDB}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}

  database:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env # Puedes especificar el archivo .env si es necesario
    volumes:
      - ~/database/nest:/var/lib/mysql
